# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: OpenJDK-7
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM openjdk:7

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
