FROM php:7.4-fpm

# COPY pip.conf /root/.pip/pip.conf
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
# RUN sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list && \
#     sed -i 's/security.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list && \
RUN cat /etc/apt/sources.list && \
    # 系统更新
    DEBIAN_FRONTEND=noninteractive && \
    apt update && apt upgrade -y &&\
    # 安装组件
    apt install -y --no-install-recommends \
    bash \
    unzip \
    openssh-client \
    wget \
    curl \
    libcurl4 \
    #imap-dev \
    openssl \
    git \
    python3 \
    augeas-lenses \
    ca-certificates \
    dialog \
    autoconf \
    make \
    gcc \
    # 构件时依赖
    python3-dev \
    libzip-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libmcrypt-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxslt-dev \
    libffi-dev \
    libsqlite3-dev \
    libpq-dev \
    python3-pip && \
    # 扩展安装
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) iconv pdo_mysql pdo_sqlite pgsql pdo_pgsql mysqli gd exif intl xsl json soap dom zip opcache bcmath && \
    pecl install xdebug && \
    pecl install runkit7-alpha && \
    pecl install uopz && \
    pecl install -o -f redis && \
    echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini && \
    # echo "extension=runkit7.so" > /usr/local/etc/php/conf.d/runkit7.ini && \
    # Imagick
    chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions imagick && \
    docker-php-source delete && \
    # Composer相关部分
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --quiet --install-dir=/usr/bin --filename=composer && \
    rm composer-setup.php && \
    # composer config -g repos.packagist composer https://mirrors.cloud.tencent.com/composer/ && \
    # composer global require hirak/prestissimo && \
    # composer global require slince/composer-registry-manager ^2.0 && \
    # composer repo:use tencent && \
    # composer clearcache && \
    # Python设定
    # update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && \
    # update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1 && \
    # pip3 install -U pip && \
    # 清理
    apt remove gcc augeas-lenses python3-dev make autoconf -y && apt autoremove -y && \
    apt remove -y \
    libzip-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libmcrypt-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libicu-dev \
    libxslt-dev \
    libffi-dev \
    libsqlite3-dev \
    libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    # 处理用户的部分
    addgroup --gid 1000 www && \
    adduser --disabled-password --gecos "" --uid 1000 --gid 1000 www
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
