# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AmazonCorretto-16
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM amazoncorretto:16-alpine

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
