# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AdoptOpenJDK-11-Hotspot
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM adoptopenjdk/openjdk11:debian

RUN apt update && \
    apt install -y --no-install-recommends bash curl wget && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
