# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AdoptOpenJDK-16-Hotspot
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM adoptopenjdk/openjdk16:alpine-slim

LABEL org.opencontainers.image.authors="echoes@yqemail.com"
LABEL org.opencontainers.image.vendor="YunQiaoLD"

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget tzdata && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
