# ----------------------------------
# Pterodactyl Core Dockerfile
# Environment: AzulZulu-16
# Minimum Panel Version: 0.6.0
# ----------------------------------
FROM azul/zulu-openjdk-alpine:16

LABEL org.opencontainers.image.authors="echoes@yqemail.com"
LABEL org.opencontainers.image.vendor="YunQiaoLD"

RUN apk --no-cache update && \
    apk --no-cache add bash curl wget tzdata && \
    adduser -D -h /home/container container

USER container
ENV  USER container
ENV  HOME /home/container

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
