name: 构建 openjdk-11 镜像

on:
  push:
    paths:
      - "pterodactyl/base/java/Dockerfile-openjdk-11"
      - "pterodactyl/base/java/entrypoint.sh"
      - ".github/workflows/openjdk-11.yml"

env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}

# 任务
jobs:
  build-openjdk-11:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建 openjdk-11 镜像
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
          path: ./pterodactyl/base/java
          dockerfile: ./pterodactyl/base/java/Dockerfile-openjdk-11
          registry: docker.io
          repository: gzzchh/pter-base
          tags: openjdk-11

  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-openjdk-11
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --auth ./sync-tool/auth.json --images ./pterodactyl/base/java/openjdk-11.yml
