name: 构建 PHP-FPM 镜像

# 触发条件：在 push 到 master 分支后
on:
  push:
    # paths:
    #   - "php-fpm/**"

# 任务
jobs:
  build-php-fpm-73:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建 PHP-FPM-73 镜像
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
          path: ./php-fpm
          dockerfile: ./php-fpm/Dockerfile.php.73
          registry: docker.io
          repository: gzzchh/stacks
          tags: php-fpm-73

  build-php-fpm-74:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建 PHP-FPM-74 镜像
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
          path: ./php-fpm
          dockerfile: ./php-fpm/Dockerfile.php.74
          registry: docker.io
          repository: gzzchh/stacks
          tags: php-fpm-74

  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-php-fpm-73
      - build-php-fpm-74
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 3 --auth ./sync-tool/auth.json --images ./php-fpm/php-fpm.yml
