name: 构建 pter-steam-mordhau 镜像
on:
  push:
    paths:
      - pter/steam/mordhau/Dockerfile
      - pter/steam/mordhau/entrypoint.sh
      - .github/workflows/pter-steam-mordhau.yml
  schedule:
    - cron: 45 6 5 * *
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  ACR_XL_USERNAME: ${{ secrets.ACR_XL_USERNAME }}
  ACR_XL_PASSWORD: ${{ secrets.ACR_XL_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
jobs:
  build-pter-steam-mordhau:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: 登陆到 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: 构建 pter-steam-mordhau 镜像
        uses: docker/build-push-action@v2
        with:
          context: pter/steam/mordhau
          file: pter/steam/mordhau/Dockerfile
          push: true
          tags: gzzchh/pter-steam:mordhau
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-pter-steam-mordhau
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images pter/steam/mordhau/mordhau.yml
