name: 构建 stacks-v2ray 镜像
on:
  push:
    paths:
      - stacks/v2ray/Dockerfile
      - stacks/v2ray/entrypoint.sh
      - .github/workflows/stacks-v2ray.yml
  schedule:
    - cron: 25 7 * * 5
env:
  TKE_USERNAME: ${{ secrets.TKE_USERNAME }}
  TKE_PASSWORD: ${{ secrets.TKE_PASSWORD }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  ACR_XL_USERNAME: ${{ secrets.ACR_XL_USERNAME }}
  ACR_XL_PASSWORD: ${{ secrets.ACR_XL_PASSWORD }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
  HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
jobs:
  build-stacks-v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 设定 Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: 登陆到 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: 构建 stacks-v2ray 镜像
        uses: docker/build-push-action@v2
        with:
          context: stacks/v2ray
          file: stacks/v2ray/Dockerfile
          push: true
          tags: gzzchh/stacks:v2ray
  sync-back:
    runs-on: ubuntu-latest
    needs:
      - build-stacks-v2ray
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 准备同步工具
        run: bash ./sync-tool/tools.sh
      - name: 搬回国内
        run: ./image-syncer -r 5 --proc 16 --auth ./sync-tool/auth.json --images stacks/v2ray/v2ray.yml
